1. Create an array of 6 zeros
2. Create an array of 6 ones
3. Create an array of 6 fives


In [2]:
import numpy as np
arr1 = np.zeros(6)
print(arr1)
arr2 = np.ones(6)
print(arr2)
arr3 = np.ones(6)*5
print(arr3)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5.]


4. Create an array of integers from 1 to 99
5. Create an array of all the odd integers ranging from 1 to 99

In [3]:
arr = np.arange(1,99)
print("Array 1 to 99 = ",end="")
print(arr)
print()
print()
print("Array 1 to 99 odd =" ,end="")
arr4 = np.arange(1,99,2)
print(arr4)

Array 1 to 99 = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98]


Array 1 to 99 odd =[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97]


6. Create a 2X2 matrix filled with values from 1 to 4
7. Create a 3X3 matrix filled with values from 9 to 17

In [4]:
mat = np.arange(1,5).reshape((2,2))
print("2 x 2 = ",end="")
print(mat)
print()
print()
mat1  = np.arange(9,18).reshape((3,3))
print("3 x 3 = ",end="")
print(mat1)

2 x 2 = [[1 2]
 [3 4]]


3 x 3 = [[ 9 10 11]
 [12 13 14]
 [15 16 17]]


8. Make an identity matrix of 4X4
9. With the help of Numpy generate a random nos in between 0 to 1
10. Create 10 points that are space linearly from each.

In [5]:
mat = np.eye(4)
print("Identity matrix = ",mat)
print()
print()
rand = np.random.randint(0,2)
print("Random between 0 and 1 = ",rand)
print()
lin = np.linspace(0,1,10)
print("Equal spaces between 0 to 1 = ",lin)

Identity matrix =  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random between 0 and 1 =  1

Equal spaces between 0 to 1 =  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


11. Compare two 3d array and display the results in terms of true and false.


In [142]:
a = np.random.randint(10,15,size=(3,3))
b = np.random.randint(10,15,size=(3,3))
print(a)
print()
print(b)
print()
print(a==b)


[[12 14 13]
 [13 14 10]
 [10 10 10]]

[[11 13 11]
 [14 14 10]
 [10 11 12]]

[[False False False]
 [False  True  True]
 [ True False False]]


12. Create a null vector of size 20 where the 6th value should be updated as 5.


In [6]:
arr = np.zeros(20)
print("Before changing Values = ",arr)
arr[6] = 5
print("After changing Values = ",arr)

Before changing Values =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After changing Values =  [0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


13. Reverse an array of size 100 using numpy.


In [7]:
arr = np.random.randint(0,50,size = (1,50))
print("Array before Reverse = ",arr)
arr = np.flip(arr)
print()
print("Array after reverse = ",arr)

Array before Reverse =  [[ 7 33  9 44 17 12 21 23 37 22  1 38 30 21 33 19 25 11 24  8 12 46 32 25
   8 38  1 40  6  7 15 37 23 24 10 42 35 20 37 33  2 49  8 14 28 32 14 19
  37 20]]

Array after reverse =  [[20 37 19 14 32 28 14  8 49  2 33 37 20 35 42 10 24 23 37 15  7  6 40  1
  38  8 25 32 46 12  8 24 11 25 19 33 21 30 38  1 22 37 23 21 12 17 44  9
  33  7]]


14. Find the minimum and maximum values of a 20X20 array using numpy.


In [8]:
arr = np.random.randint(0,100,size=(20,20))
print("Array = " , arr)
print("Maximum = ",np.max(arr))
print("Minimum = ",np.min(arr))


Array =  [[26 46 72 34 48 34 94 50 80 34 99 51 22  1  5 61 25 17 90 76]
 [96 56 43 98 67 97  2 66 64  3 68 54 25 58 61 73 61 58  5 70]
 [83 82 97 33 89 70 52 56 87  7 14 18 62 28 60 38 80 92 38 56]
 [99 94 87 35 14 28 57 10 32 92 53 51 95 90 84 10 86 93 99 65]
 [49 84 26 33 62 95 29  3 32 68  3  1 70  2 16 13  0 17 44 49]
 [74 33 17 44 70 55 17 23 80 55 18 30 35 95 15 68 64 27 83 80]
 [60 28 28 89 19 62 42 83 93 99 63  4 70 40 59 66 96 91 13 17]
 [53 83 17 82 89 86 76 48 52 42 55 15 26 22 79 20  1 53 16  0]
 [76 33 79 92 39 92 83 53 78 28 46 15 61 67 68 42 44 63  1 30]
 [69 36 17 50 37 57 11 77 65 17 31 27  8  9 46 37 93 34 54 10]
 [75 57 36  2 74 82 22 40 92 81 96 95 60 75  4 63 18 76 41 80]
 [81 93 68  2 84 10 42 68 98 95 94  5 56 17 20 86 35 92 44 13]
 [35 17 89  4 26 64 56 18  6 57 69 21 17 37 56 33 28 38 25  1]
 [99 31 44 82  1 47 76 57 94 58  9 60 37 63 60  6 15 39 13 55]
 [14 86 67  2 58 72 74 89  9  6 47 63 12 83 93 97 87 97 63 92]
 [86 96  2 28 26 64 82 29 22 62 66 12 56 36 31

15. Find mean value of a randomly generated array of size 50.

In [9]:
arr = np.random.randint(0,100,size=(1,50))
print("Array = ",arr)
print("Mean = ",np.mean(arr))


Array =  [[70 66 64  5 51 82 40 81 32 99 69 91 90 43 60 26 68 99 50  7 47  8 43 43
  76 89 81 74  4 21 23  4 55 78 28 85 68 51 72 23 80 67 19 89 46 96 98 41
  29 89]]
Mean =  56.4


16. “ A 20 X20 array filled with zeros at all borders and all 1’s inside”-create such array.

In [10]:
arr = np.ones((20,20))
arr[1:-1,1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

17. Create an array of size 10X10 with 10 element valued as nan

In [11]:
arr = np.full((10,10),np.nan)
np.append(arr,np.random.randint(0,10,size = (9,10)))
arr[1:10] = 1
print(arr)

[[nan nan nan nan nan nan nan nan nan nan]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


18. Create a 4X4 matrix and the values just below the diagonal is 9 8 7

In [12]:
arr = np.diag(9-np.arange(3),k=-1)
print(arr)

[[0 0 0 0]
 [9 0 0 0]
 [0 8 0 0]
 [0 0 7 0]]


19. Create a check board pattern using numpy

In [13]:
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


20. Print the dtype of int32 and float64 data type.

In [14]:
arr = np.random.randint(1,10,size = 10)
print(arr ,"Dtype = ", arr.dtype)
arr = np.linspace(0,3,10)
print(arr,"Dtype = ", arr.dtype)

[2 8 6 3 3 6 5 5 3 8] Dtype =  int32
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ] Dtype =  float64


Pandas Practice Problems

1. Create a pandas Series using lists and dictionaries? 


In [15]:
import pandas as pd
ser1 = pd.Series([1.4,2.4,3.1,2.3])
print("Using lists:")
print(ser1)
print()
print("Using dictionary")
ser2 = pd.Series({"India":"New Delhi","Japan":"Tokyo","Uk":"London"})
print(ser2)

Using lists:
0    1.4
1    2.4
2    3.1
3    2.3
dtype: float64

Using dictionary
India    New Delhi
Japan        Tokyo
Uk          London
dtype: object


2. Create series using NumPy functions in Pandas? 


In [16]:
ser = pd.Series(np.linspace(1,10,5))
print(ser)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64


3. Find index and values of series in Pandas? 

In [17]:
ser2 = pd.Series({"India":"New Delhi","Japan":"Tokyo","Uk":"London"})
print(ser2)
print()
print(ser2.values)
print()
print(ser2.index)

India    New Delhi
Japan        Tokyo
Uk          London
dtype: object

['New Delhi' 'Tokyo' 'London']

Index(['India', 'Japan', 'Uk'], dtype='object')


4. How to specify an index while creating Series in Pandas? Find Length Size and Shape of a
Series in Pandas?

In [25]:
a = ['Australia', 'Iceland', 'India', 'United Kingdom', 'United States']
b = ['Canberra', 'Reykjavik', 'New Delhi', 'London', 'Washington D.C']
s = pd.Series(b, index=a)
print(s)
print()
print("Length = ",len(s))
print("Size = ",s.size)
print("Shape = ",s.shape)


Australia               Canberra
Iceland                Reykjavik
India                  New Delhi
United Kingdom            London
United States     Washington D.C
dtype: object

Length =  5
Size =  5
Shape =  (5,)


5. Find the first or last few rows from a Series in Pandas?

In [34]:
a = ['Australia', 'Iceland', 'India', 'United Kingdom', 'United States']
b = ['Canberra', 'Reykjavik', 'New Delhi', 'London', 'Washington D.C']
s = pd.Series(b, index=a)
print("Head = ",s.head(1))
print()
print("Tail = ",s.tail(1))


Head =  Australia    Canberra
dtype: object

Tail =  United States    Washington D.C
dtype: object


6. Demonstrate possible missing value analysis approaches using any real world data.


In [55]:
file = pd.read_csv("britt.csv")
print(file)
print()
print("Number of Null in the file:")
print(file.isnull().sum())
new_file = file.fillna(0)
print()
print("New file with all Nan to 0:")
print(new_file)

    TK104  TK105  TK107
0   254.0  263.0    338
1   440.0    NaN    470
2   501.0    NaN    558
3   368.0  451.0    426
4     NaN  403.0    306
5     NaN  690.0    558
6     NaN  460.0    358
7   697.0  709.0    733
8   697.0  709.0    733
9   476.0  542.0    539
10  188.0  223.0    240
11  525.0  659.0    628

Number of Null in the file:
TK104    3
TK105    2
TK107    0
dtype: int64

New file with all Nan to 0:
    TK104  TK105  TK107
0   254.0  263.0    338
1   440.0    0.0    470
2   501.0    0.0    558
3   368.0  451.0    426
4     0.0  403.0    306
5     0.0  690.0    558
6     0.0  460.0    358
7   697.0  709.0    733
8   697.0  709.0    733
9   476.0  542.0    539
10  188.0  223.0    240
11  525.0  659.0    628


7. Checking the duplicate rows and columns using pandas.

In [56]:
print(file.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
dtype: bool


8. Suppose you have height and weight data for a group of people. For example: Heights are in
feet, like 6.5, and weight is in grams, like 80000. In many machine learning situations, you
want to normalize the data — scale the data so that the values in different columns have
roughly the same magnitude so that large values (like the weight) don’t overwhelm smaller
values (like the heights).
Create a raw data of minimum 40 records of height and weight in above mentioned format
and use MinMax Normalization to normalize the weights in the range from (-10.0 to 10) as
well as use Z-score to normalize the weights

In [132]:
a = np.random.randint(140,190,size = 40)
a=a*0.0328084
b = np.random.randint(40000,140000,size = 40)
dict = {"Height":a,"Weight":b}

def min_max(file):
    # copy the dataframe
    file_norm = file.copy()
    # apply min-max scaling
    for column in file_norm.columns:
        file_norm[column] = (file_norm[column] - file_norm[column].min()) / (file_norm[column].max() - file_norm[column].min())
        
    return file_norm


normalized = min_max(pd.DataFrame(dict))
normalized


Height    Weight
0   0.804348  0.640779
1   0.586957  0.964805
2   0.239130  0.476859
3   1.000000  0.000000
4   0.500000  0.748621
5   0.565217  0.183803
6   0.413043  0.069989
7   0.739130  0.493773
8   0.847826  0.070089
9   0.152174  0.249666
10  0.434783  0.302742
11  0.086957  1.000000
12  0.021739  0.743161
13  0.000000  0.052642
14  0.217391  0.053465
15  0.869565  0.384630
16  0.739130  0.756305
17  0.652174  0.525287
18  0.804348  0.566575
19  0.760870  0.075616
20  0.456522  0.723790
21  0.652174  0.402922
22  0.478261  0.103950
23  0.021739  0.516491
24  0.478261  0.475291
25  0.565217  0.059025
26  0.521739  0.995886
27  0.413043  0.092641
28  0.586957  0.360222
29  0.543478  0.619918
30  0.565217  0.339972
31  0.630435  0.393648
32  0.739130  0.750122
33  0.043478  0.839116
34  0.260870  0.101348
35  0.695652  0.762454
36  0.913043  0.656536
37  0.000000  0.216206
38  0.239130  0.797204
39  0.282609  0.464438